# Jekyll configuration

name: Kwon Dae Hyun/권대현
description: Hi, I'm Soongsil university student major in SW. I can deal with C, C++, JAVA. However, still polishing it. Thank you for visiting. 안녕하세요, 저는 숭실대학교에서 SW를 전공하고 있는 권대현입니다. C, C++, JAVA를 전공하고 있으며, 아직 실력을 갈고 닦고 있습니다. 잘 부탁 드립니다.

# Url is currently only used only for the RSS feed in feed.xml
url: http://neoskyclad.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: '/neoskyclad.github.io'

author: Pavel Makhov
copyright: 2015-2018

share:
  facebook: false
  twitter: false
  gplus: false
  linkedin: false
  pinterest: false
  email: true

social:
  github: neoskyclad
  stackoverflow: ''
  linkedin:
  instagram: 'hyun_dda_gun'
  lastfm: ''
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: streetturtle
comments: false

permalink: /:year/:month/:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
